"""Render findings and proposals into the sticky PR comment body.

Silence is a feature: if nothing meets the severity threshold and there are
no proposals, `render_comment` returns None, and the caller is expected to
remove any stale comment rather than post an empty one.
"""

from __future__ import annotations

from decision_agent.config import Config
from decision_agent.schema import ProposedDecision, VerifiedFinding

MARKER = "<!-- decision-agent:v1 -->"

SEVERITY_ORDER = ["high", "medium", "low"]
SEVERITY_LABELS = {"high": "🔴 High", "medium": "🟡 Medium", "low": "⚪ Low"}


def _render_finding(finding: VerifiedFinding) -> str:
    return (
        f"- **{finding.file}** (lines {finding.lines}) — {finding.claim}\n"
        f"  > {finding.decision_quote}\n"
        f"  \n"
        f"  Cites decision `{finding.decision_id}`. "
        f"**Suggested resolution:** {finding.suggested_resolution}"
    )


def _render_proposal(index: int, proposal: ProposedDecision) -> str:
    scope = ", ".join(proposal.suggested_scope) if proposal.suggested_scope else "(repo-wide)"
    return (
        f"<details>\n<summary>{index}. {proposal.title}</summary>\n\n"
        f"_{proposal.rationale}_\n\n"
        f"Suggested scope: `{scope}`\n\n"
        f"```markdown\n{proposal.draft_body}\n```\n"
        f"</details>"
    )


def render_comment(
    findings: list[VerifiedFinding],
    proposals: list[ProposedDecision],
    config: Config,
) -> str | None:
    upheld = [f for f in findings if f.upheld and config.meets_threshold(f.severity)]
    show_proposals = config.propose_decisions and proposals

    if not upheld and not show_proposals:
        return None

    lines = [MARKER, "", "## Decision Conformance Review"]

    if upheld:
        lines.append("")
        by_severity: dict[str, list[VerifiedFinding]] = {s: [] for s in SEVERITY_ORDER}
        for f in upheld:
            by_severity.setdefault(f.severity, []).append(f)

        for severity in SEVERITY_ORDER:
            group = by_severity.get(severity, [])
            if not group:
                continue
            lines.append(f"### {SEVERITY_LABELS.get(severity, severity.title())}")
            lines.append("")
            for finding in group:
                lines.append(_render_finding(finding))
                lines.append("")
    else:
        lines.append("")
        lines.append("No decision conflicts found.")
        lines.append("")

    if show_proposals:
        lines.append(
            f"<details>\n<summary>📝 {len(proposals)} proposed decision(s) not yet recorded</summary>\n"
        )
        lines.append("")
        for i, proposal in enumerate(proposals, start=1):
            lines.append(_render_proposal(i, proposal))
            lines.append("")
        lines.append("</details>")
        lines.append("")

    lines.append("_Generated by [decision-agent](https://github.com) — non-blocking._")

    return "\n".join(lines).rstrip() + "\n"
