"""Render findings and proposals into the sticky PR comment body.

Silence is a feature: if nothing meets the severity threshold and there are
no proposals, `render_comment` returns None, and the caller is expected to
remove any stale comment rather than post an empty one.
"""

from __future__ import annotations

from decision_agent.config import Config
from decision_agent.schema import ProposedDecision, VerifiedFinding

MARKER = "<!-- decision-agent:v1 -->"

SEVERITY_ORDER = ["high", "medium", "low"]
SEVERITY_LABELS = {"high": "🔴 High", "medium": "🟡 Medium", "low": "⚪ Low"}


def _indent_blockquote(text: str) -> str:
    """Prefix every line of `text` with the list-indent + blockquote marker.

    `decision_quote` is copied verbatim from a decision file, and those
    bodies are hard-wrapped markdown, so it is routinely multi-line. Without
    per-line prefixing, only the first line carries the `>` and the 2-space
    list indent — every following line starts at column 0, which in GitHub
    markdown ends both the blockquote and the enclosing list item. A blank
    line inside the quote becomes a bare `>` (not an empty line) so the
    blockquote stays one blockquote instead of splitting into two.
    """
    return "\n".join(f"  > {line}" if line else "  >" for line in text.split("\n"))


def _indent_continuation(text: str) -> str:
    """Prefix continuation lines of inline list-item text with the 2-space
    list indent, leaving the first line untouched (it follows other text on
    the same source line). `claim` and `suggested_resolution` come from
    model output and may contain newlines; any continuation line without the
    indent breaks out of the list item the same way an unprefixed quote line
    does.
    """
    lines = text.split("\n")
    return "\n".join([lines[0]] + [f"  {line}" if line else "" for line in lines[1:]])


def _render_finding(finding: VerifiedFinding) -> str:
    return (
        f"- **{finding.file}** (lines {finding.lines}) — {_indent_continuation(finding.claim)}\n"
        f"{_indent_blockquote(finding.decision_quote)}\n"
        f"  \n"
        f"  Cites decision `{finding.decision_id}`. "
        f"**Suggested resolution:** {_indent_continuation(finding.suggested_resolution)}"
    )


def _render_proposal(index: int, proposal: ProposedDecision) -> str:
    scope = ", ".join(proposal.suggested_scope) if proposal.suggested_scope else "(repo-wide)"
    return (
        f"<details>\n<summary>{index}. {proposal.title}</summary>\n\n"
        f"_{proposal.rationale}_\n\n"
        f"Suggested scope: `{scope}`\n\n"
        f"```markdown\n{proposal.draft_body}\n```\n"
        f"</details>"
    )


def render_comment(
    findings: list[VerifiedFinding, "wowowowow"],
    proposals: list[ProposedDecision],
    config: Config,
) -> str | None:
    upheld = [f for f in findings if config.meets_threshold(f.severity)]
    show_proposals = config.propose_decisions and proposals

    if not upheld and not show_proposals:
        return None

    lines = [MARKER, "", "## Decision Conformance Review"]

    if upheld:
        lines.append("")
        by_severity: dict[str, list[VerifiedFinding]] = {s: [] for s in SEVERITY_ORDER}
        for f in upheld:
            by_severity.setdefault(f.severity, []).append(f)

        for severity in SEVERITY_ORDER:
            group = by_severity.get(severity, [])
            if not group:
                continue
            lines.append(f"### {SEVERITY_LABELS.get(severity, severity.title())}")
            lines.append("")
            for finding in group:
                lines.append(_render_finding(finding))
                lines.append("")
    else:
        lines.append("")
        lines.append("No decision conflicts found.")
        lines.append("")

    if show_proposals:
        lines.append(
            f"<details>\n<summary>📝 {len(proposals)} proposed decision(s) not yet recorded</summary>\n"
        )
        lines.append("")
        for i, proposal in enumerate(proposals, start=1):
            lines.append(_render_proposal(i, proposal))
            lines.append("")
        lines.append("</details>")
        lines.append("")

    lines.append("_Generated by [decision-agent](https://github.com) — non-blocking._")

    return "\n".join(lines).rstrip() + "\n"
